### ISSUE TITLE
Support for merging duplicate keys in a config file

### ISSUE THREAD

**Issue by jhalterman** [hassankhan/config#89]
I'm wondering if you'd consider adding support for merging duplicate keys in a config file. My use case for this is wanting to have multiple environment config sections in a file since it makes config easier to organize by functionality. Example:

```yml
# Messaging config
dev:
  msg-host: foo

prod:
  msg-host: bar

# Database config
dev:
  db-host: foo

prod:
  db-host: bar
```

Ideally, this would be merged when loaded to:

```yml
dev:
  msg-host: foo
  db-host: foo

prod:
  msg-host: bar
  db-host: bar
```

While I could just write my config fully merged by environment, with a lot of config and multiple environments it's easier to maintain when it's organized by functionality.
